// <auto-generated />
namespace tess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class validacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201808011655551_validacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
